### ISSUE TITLE
Proposal: silverstripe-calendar

### ISSUE THREAD

**Issue by robbieaverill** [silverleague/silverleague.github.io#2]
# silverleague/silverstripe-calendar

**Specification**: https://silverleague.github.io/draft/silverstripe-calendar

## Introduction

This is a porting proposal for [titledk/silverstripe-calendar](https://github.com/titledk/silverstripe-calendar).

The calendar for SilverStripe 3.x is a solid base for all your calendaring needs, it's built to be flexible and configurable so that it fits to most scenarios - both for web sites with public events, and web apps with private events - or a combination hereof.

## Framework support

^3.1

## Use case

TBC.

## Functionality

- [x] Extensible. Customize it any way you want, while the basic concepts are taken care of.
- [x] Solid, opinionated models.
- [x] Event/Calendar/Category relations allowing complex filtering.
- [x] Public/Private events.
- [x] All features are configurable, so if you only need the basics, you can turn the rest off.
- [x] Comprehensive calendar/event administration.
- [x] JavaScript enhanced edit event form, usable both on frontend and backend, with date picker, time picker and dropdown, and duration dropdown, still allowing manual inputs
- [x] Listing of events on the frontend through the CalendarPage
- [x] Frontend calendar view, using the fullcalendar jQuery plugin
- [x] Event Registrations (this might be moved to an external module)
- [x] Calendar colors with configurable color options, and JS color palette field (works on both frontend and backend) - shading calendars allow for holiday calendars etc. to appear in the background

## Wish list

- [ ] More comprehensive unit tests
- [ ] Recurring events
- [ ] Everything should be translatable

## License

To be re-released under the MIT license.

**Comment by Firesphere** [comment]
Unless tests are added before pulling this in, I'd say no. We need to (harshly maybe?) stick to what we decide on, and tests and testcoverage is one of the big things here.

**Comment by robbieaverill** [comment]
I'm inclined to agree. What is the alternative? Make pull requests against the repo until it's tested?

**Comment by Firesphere** [comment]
Tests and a new stable release with those tests, before I would reconsider my rejection. So yes, I would prefer a test-coverage of at least 60% before accepting (which is actually very low!)

On functionality and consistent support, I definitely believe this module fits the requirements.

**Comment by robbieaverill** [comment]
>On functionality and consistent support, I definitely believe this module fits the requirements.

But it'd be SilverLeague that'd provide the support yeah? :)

This is a catch 22 really - if we want the module we'll need to work on it before we take it.

**Comment by anselmdk** [comment]
To clarify, I proposed to @robbieaverill to hand this module over to SilverLeague as I'd love it to live on, but don't feel I have the resources at the moment to keep on maintaining it.
@robbieaverill asked me to comment on it's strong and weak points.
As a starter you might want to read this blog post: https://www.silverstripe.org/blog/managing-events-with-silverstripe-a-new-calendar-module/

## Strengths

* I spent quite some time on drafting the initial data model and have used it in production on a few sites where it's been battle tested, both for just public events, but also for private calendars and events.
* Has somewhat been kept up to date so it should work with everything `3.x`
* Self-populating demo site: http://calendar.demo.title.dk / https://github.com/titledk/silverstripe-calendar-demo
* Configurable (but uses a home-build pre-3.1 configuration system - would need to be upgraded)
* Pretty comprehensive README file

## Weaknesses

* No unit tests
* Beyond updates and fixes there has not been much new development on it since it's public release in November 2014
* It misses recurring events (needs to be developed)


See also [roadmap](https://github.com/titledk/silverstripe-calendar#roadmapideasplans) and [weaknesses](https://github.com/titledk/silverstripe-calendar#weak-points-at-the-moment) in the README

**Comment by robbieaverill** [comment]
I've added a +1 vote from me.

**Comment by anselmdk** [comment]
I'll do the same ;)

**Comment by robbieaverill** [comment]
@Firesphere is this a module you'd like to take maintainership of?

Regarding test coverage, I'm sure we could add it and release a minor version update at the point we've taken it over (or before) without much stress.

**Comment by Firesphere** [comment]
I'll have to dive into the codebase a bit, but sure :)

**Comment by robbieaverill** [comment]
It doesn't sound like there's a huge driver for this, do we want to abandon?

**Comment by anselmdk** [comment]
Yes, let's abandon
