### ISSUE TITLE
Proposal: silverstripe-bootstrap4-forms

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverleague.github.io#8]
Probably resolved with SS4 going to BS4, but recording the idea for historical purposes

**Comment by zanderwar** [comment]
I looked into the templates and it doesn't really make it easy for you to add classes to the actual input field, in particular the one required by bootstrap `form-control`, adding functionality for input groups and button groups would be a great addition.

I know the agency I work for would definitely appreciate it

**Comment by zanderwar** [comment]
Just a note, I had asked unclecheese if he intends to update his [bootstrapforms](https://github.com/unclecheese/silverstripe-bootstrap-forms) module for Bootstrap 4. He was pretty adamant that he doesn't see that happening. 

So this is still fine to go ahead with but it'd probably be better to just submit a PR with BS4 support to the repo above

**Comment by Firesphere** [comment]
Yeah, as updating is pretty much the same as rewriting because of all the changes. Too much changed between BS2 and BS3 already.

Maintainer/developer roles would preferably go to a seasoned frontender. (That is NOT me)

**Comment by robbieaverill** [comment]
SilverStripe 4 CMS uses Bootstrap 4 - if this is aimed at the frontend rather than the CMS then I think the [CWP starter theme](https://github.com/silverstripe/cwp-starter-theme) is likely to become a more generic implementation of Bootstrap for frontend themes. At the moment it's using Bootstrap 3, but I'd expect it to be updated to Bootstrap 4 at some point in the next year or two.

Feel free to reopen if you'd like to =)
